### ISSUE TITLE
Any chance to make new release?

### ISSUE THREAD

**Issue by kloczek** [TelepathyIM/telepathy-glib#1]
I think that it would be good to flush all already commited changes and make new release :)

**Comment by Kaffeine** [comment]
Hello. I have access to freedesktop.org and technically I can make a release, but I'm not a glib developer and not interested in glib development.
OTOH there is a number of Telepathy components that depend on tp-glib and have no replacement in Qt.
I think it makes sense to make a release, especially if there'll be a fix for tests (https://github.com/TelepathyIM/telepathy-glib/issues/2).

I'll try to check the tests and make a new release during the next week.

**Comment by Thaodan** [comment]
Any news on that?

**Comment by Kaffeine** [comment]
We have to figure out how to make it. Let's see...

1. The latest released version is 0.24.1 and there is branch [telepathy-glib-0.24 ](https://github.com/TelepathyIM/telepathy-glib/tree/telepathy-glib-0.24)
2. All commits (port to python 3) and fixes landed `master` branch
3. The NEWS file there says "Version 0.25.0"
4. The version in [configure.ac](https://github.com/TelepathyIM/telepathy-glib/blob/master/configure.ac) (`master`) is `0.24.1.1`.
5. Branch 0.24 is "zero commits ahead of master"

I thought that we'll have to release 0.26.0 but hmm, I had no idea about `#4` and `#5`.
Now I think that the better option is to change 0.25.0 entry in `NEWS` to 0.24.2, push master (fast-forward) to branch 0.24 and release the result as `0.24.2`.

**Comment by Thaodan** [comment]
I'm currenty working on finnishing the work that was done to port away from 
dbus-glib. Maybe you make new release (25.0} so my changes can be merged then 
after that.

**Comment by aperezbios** [comment]
Hi folks, any progress on making a release here? @Thaodan? @Kaffeine? It would be very helpful to have a release with the memory leak fixed :) We still use telepathy, as well as telepathy-gabble in Sugar Desktop.

**Comment by Kaffeine** [comment]
> Hi folks, any progress on making a release here? @Thaodan? @Kaffeine? It would be very helpful to have a release with the memory leak fixed :) We still use telepathy, as well as telepathy-gabble in Sugar Desktop.

You're right. I'll try hard to carry out the plan (0.24.2) this evening.

**Comment by Kaffeine** [comment]
I pushed signed tag `telepathy-glib-0.24.2`: https://github.com/TelepathyIM/telepathy-glib/tags

The changes also pushed to branch [telepathy-glib-0.24](https://github.com/TelepathyIM/telepathy-glib/tree/telepathy-glib-0.24), but not merged to master yet.

I spent some time on vala-related stuff but I had to comment-out related checks. :-(

@aperezbios, @kloczek, and everyone who care :) — please check the release and confirm that the release work for you.

The release is also already uploaded to the official releases. Once you confirm, I will sync the code to gitlab.freedesktop.org and send the release mail.

## Release mail
tarball: http://telepathy.freedesktop.org/releases/telepathy-glib/telepathy-glib-0.24.2.tar.gz
signature: http://telepathy.freedesktop.org/releases/telepathy-glib/telepathy-glib-0.24.2.tar.gz.asc
git: http://cgit.freedesktop.org/telepathy/telepathy-glib

### Enhancements:

- Port build tools to Python 3 (Alexey Andreyev)
- Update and fix tests for Python 3 (Jakub Kulík)

### Fixes:

- stop hardcoding python's path in .py scripts (fd.o #76495, Guillaume)
- fixed some code issues discovered by compiling with clang (fd.o #79006, Guillaume)
- replaced tp_verify_* with G_STATIC_ASSERTs, fixing the build with more recent gtk-doc (Simon)
- autogen.sh: run gtkdocize from $srcdir in out-of-source builds (fd.o #94391, Philip Withnall)
- tests: fix build failure with glib >= 2.46 due to duplicate test paths (fd.o #92245, George Kiagiadakis)
- tests: Fix a service file path to fix the build with installed tests (fd.o #90991, Philip Withnall)
- call-channel: fix a memory leak (Fabrice Bellet)
- debug-sender: fix messages queue locking (Fabrice Bellet)
- TpBasePasswordChannel: fix gtk-doc comment for finished signal (Ting-Wei Lan)
- protocol: fix a memory leak (Ivaylo Dimitrov)

**Comment by Kaffeine** [comment]
Officially released: https://lists.freedesktop.org/archives/telepathy/2021-February/007081.html (with one more fix from Jolla)
